Insert into CATEGORIES (ID,CATEGORY_NAME) values ('1','SUV');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('2','Van/Minivan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('3','Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('4','Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('5','Hatchback');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('6','Pickup');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('7','Hatchback, Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('8','Coupe, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('9','Coupe, Sedan, Hatchback');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('10','Coupe');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('11','Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('12','Wagon, Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('13','Sedan, Hatchback');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('14','Convertible, Sedan, Coupe');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('15','Sedan, Convertible, Coupe');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('16','Coupe, Sedan, Wagon, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('17','Coupe, Convertible, Sedan, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('18','Sedan, Coupe, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('19','Coupe, Sedan, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('20','Sedan, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('21','Convertible, Coupe, Hatchback');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('22','SUV2020');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('23','Convertible, Coupe');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('24','Sedan, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('25','Coupe, Convertible, Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('26','Coupe, Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('27','Hatchback, Sedan, Coupe');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('28','Coupe, Wagon, Sedan, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('29','Sedan, Coupe');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('30','SUV1992');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('31','Convertible, Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('32','Hatchback, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('33','Sedan, Coupe, Wagon, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('34','Coupe, Hatchback, Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('35','Sedan, Coupe, Convertible, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('36','Convertible, Coupe, Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('37','Convertible, Sedan, Coupe, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('38','Sedan, Hatchback, Coupe');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('39','Sedan, Coupe, Hatchback');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('40','Sedan, Wagon, Coupe, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('41','Sedan, Coupe, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('42','Coupe, Convertible, Wagon, Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('43','Convertible, Wagon, Coupe, Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('44','Wagon, Convertible, Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('45','Convertible, Wagon, Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('46','Sedan, Convertible, Coupe, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('47','Sedan, Wagon, Coupe');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('48','Sedan, Convertible, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('49','Sedan, Wagon, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('50','Coupe, Sedan, Convertible, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('51','Wagon, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('52','Hatchback, Sedan, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('53','SUV, Pickup');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('54','Sedan, Hatchback, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('55','Wagon, Sedan, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('56','Convertible, Sedan, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('57','Wagon, SUV');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('58','Hatchback, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('59','Sedan, Wagon, Hatchback');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('60','Coupe, Sedan, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('61','Convertible, Hatchback');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('62','Wagon, Sedan, Coupe');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('63','Sedan, Wagon, Convertible, Coupe');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('64','SUV, Wagon');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('65','Coupe, Hatchback, Convertible, Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('66','Wagon, Sedan, Hatchback');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('67','Hatchback, Convertible, Coupe');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('68','Hatchback, Sedan, Coupe, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('69','Hatchback, Sedan, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('70','Coupe, Hatchback, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('71','Coupe, Wagon, Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('72','Hatchback, Coupe, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('73','Hatchback, Coupe, Sedan, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('74','Coupe, Hatchback');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('75','Sedan, Hatchback, Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('76','Coupe, Convertible, Hatchback');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('77','Convertible,Sedan,Coupe');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('78','Convertible,Coupe');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('79','Coupe,Convertible');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('80','Hatchback,Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('81','Wagon,Sedan');
Insert into CATEGORIES (ID,CATEGORY_NAME) values ('82','Hatchback, Coupe');
